# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\"\x14\n\x04\x43har\x12\x0c\n\x04\x63har\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x07\x44isplay\x12\x0f\n\x07\x64isplay\x18\x01 \x01(\t\"%\n\x06Insert\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04\x63har\x18\x02 \x01(\t\"x\n\x0cInsertParams\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04\x63har\x18\x02 \x01(\t\x12\x11\n\tserver_id\x18\x03 \x01(\x05\x12\x11\n\ttumbstamp\x18\x04 \x01(\x08\x12\x11\n\ttimestamp\x18\x05 \x03(\x05\x12\x12\n\nreplica_id\x18\x06 \x01(\t\"\x17\n\x06\x44\x65lete\x12\r\n\x05index\x18\x01 \x01(\x05\"j\n\x0c\x44\x65leteParams\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\tserver_id\x18\x02 \x01(\x05\x12\x11\n\ttumbstamp\x18\x03 \x01(\x08\x12\x11\n\ttimestamp\x18\x04 \x03(\x05\x12\x12\n\nreplica_id\x18\x05 \x01(\t\"/\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0bserver_port\x18\x02 \x01(\t\"\x85\x01\n\x06Params\x12\x11\n\toperation\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0c\n\x04\x63har\x18\x03 \x01(\t\x12\x11\n\tserver_id\x18\x04 \x01(\x05\x12\x11\n\ttumbstamp\x18\x05 \x01(\x08\x12\x11\n\ttimestamp\x18\x06 \x03(\x05\x12\x12\n\nreplica_id\x18\x07 \x01(\t\"%\n\nParamsList\x12\x17\n\x06params\x18\x01 \x03(\x0b\x32\x07.Params2\x8c\x02\n\x0f\x44ocumentService\x12%\n\rInsertCommand\x12\x07.Insert\x1a\t.Response\"\x00\x12%\n\rDeleteCommand\x12\x07.Delete\x1a\t.Response\"\x00\x12\'\n\x0e\x44isplayCommand\x12\x08.Display\x1a\t.Response\"\x00\x12(\n\nSendInsert\x12\r.InsertParams\x1a\t.Response\"\x00\x12(\n\nSendDelete\x12\r.DeleteParams\x1a\t.Response\"\x00\x12.\n\x13SendPendingMessages\x12\x08.Request\x1a\x0b.ParamsList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHAR']._serialized_start=18
  _globals['_CHAR']._serialized_end=38
  _globals['_RESPONSE']._serialized_start=40
  _globals['_RESPONSE']._serialized_end=67
  _globals['_DISPLAY']._serialized_start=69
  _globals['_DISPLAY']._serialized_end=95
  _globals['_INSERT']._serialized_start=97
  _globals['_INSERT']._serialized_end=134
  _globals['_INSERTPARAMS']._serialized_start=136
  _globals['_INSERTPARAMS']._serialized_end=256
  _globals['_DELETE']._serialized_start=258
  _globals['_DELETE']._serialized_end=281
  _globals['_DELETEPARAMS']._serialized_start=283
  _globals['_DELETEPARAMS']._serialized_end=389
  _globals['_REQUEST']._serialized_start=391
  _globals['_REQUEST']._serialized_end=438
  _globals['_PARAMS']._serialized_start=441
  _globals['_PARAMS']._serialized_end=574
  _globals['_PARAMSLIST']._serialized_start=576
  _globals['_PARAMSLIST']._serialized_end=613
  _globals['_DOCUMENTSERVICE']._serialized_start=616
  _globals['_DOCUMENTSERVICE']._serialized_end=884
# @@protoc_insertion_point(module_scope)
